In [28]:
import numpy as np
import pandas as pd

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [29]:
df=pd.read_csv(r"C:\xampp816\htdocs\personal-dev\py-ds\NLP\spam_filtering\spam.csv")
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [31]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [32]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

def preprocessing(sentence):
    return ' '.join([WordNetLemmatizer().lemmatize(w, 'v') for w in "".join([c for c in sentence.lower() if c not in string.punctuation]).split() if w not in stopwords.words('english')])

df['preprocessed_message'] = df['Message'].apply(preprocessing)

df

,Category,Message,preprocessed_message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think go usf live around though
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,2nd time try 2 contact u u £750 pound prize 2 ...
5568,ham,Will ü b going to esplanade fr home?,ü b go esplanade fr home
5569,ham,"Pity, * was in mood for that. So...any other s...",pity mood soany suggestions
5570,ham,The guy did some bitching but I acted like i'd...,guy bitch act like id interest buy something e...
5571,ham,Rofl. Its true to its name,rofl true name

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(df['Category'])

In [34]:
x=df['preprocessed_message']
x

0       go jurong point crazy available bugis n great ...
1                                   ok lar joke wif u oni
2       free entry 2 wkly comp win fa cup final tkts 2...
3                     u dun say early hor u c already say
4                nah dont think go usf live around though
                              ...
5567    2nd time try 2 contact u u £750 pound prize 2 ...
5568                             ü b go esplanade fr home
5569                          pity mood soany suggestions
5570    guy bitch act like id interest buy something e...
5571                                       rofl true name
Name: preprocessed_message, Length: 5572, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x_vector=vectorizer.fit_transform(x)
x_vector.shape

(5572, 8489)

In [36]:
x_vector

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 47187 stored elements and shape (5572, 8489)>

Train Test Split

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_vector, y)

Model training

In [38]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)

Evaluation

In [39]:
from sklearn.metrics import classification_report

In [47]:
test_text = 'Free free free, grab this offer soon, offer ends soon'
test_pre=preprocessing(test_text)
test = vectorizer.transform([test_text])
res=model.predict(test)
le.inverse_transform([res[0]])[0]

'spam'

Function Creation

In [51]:
def spam_classifier(text):
    text=preprocessing(text)
    vector = vectorizer.transform([text])
    res=model.predict(vector)
    return le.inverse_transform([res[0]])[0]
text = 'Free free free, grab this offer soon, offer ends soon'
text = 'goodmorning all!'
spam_classifier(text)

'ham'